### ISSUE TITLE
A cry for better documentation ;)

### ISSUE THREAD

**Issue by dotnetCarpenter** [dionyziz/stream.js#25]
After getting this package up to date, I had some more time playing around
with `stream.js` and I find it quite hard to use. I will give two examples.

I'm building a parser and it has a lexer which reads text and convert it to tokens.
The main work of the lexer is a recursive function. It didn't work with large
pieces of text as I ran into V8's too much recursion issue (exhausting the call stack).
So I switch from using an array that was passed on recursively as an accumulator to use `stream.js`.

``` js
function lexer(str, options = { newline:false }) {
    if(str.length === 0) return new Stream
    if(regexWord.test(str)) {
        let word = regexWord.exec(str)[0],
            rest = str.substr(word.length)
        return new Stream(new Word(word), () => read(rest, options))
    }
    if(regexNewLine.test(str)) {
        let newline = regexNewLine.exec(str)[0],
            rest = str.substr(newline.length)
        if(options.newline)
            return new Stream(new NewLine(newline), () => read(rest, options))
        return read(rest, options)
    }
}
```

_Word and NewLine are token data types and Stream is `stream.js`_

After the tokenization I needed to get access to some of the tokens, enought to do something
meaningful and not too many to course a recursion issue. First I tried with `take`.

While that gave me some tokens, it didn't change the length of the stream. Imagine the
following:

``` js
let stream = lexer(str, options)
let scheduleId = setInterval(() => {
    let tokens = stream.take(64)
    parse(tokens)

    if(stream.empty())
        clearInterval(scheduleId)
}, 0)
```

The parse function will get the same 64 tokens all the time. I then tried with `drop`.
This change the length of the `stream` but the parse function was still getting the same
tokens, over and over. Since my word list has pretty similar words, it took me a while
to figure out what was going on. The two functions `take` and `drop` need to be combined.

``` js
let tokens = stream.take(64)
stream = stream.drop(64)
```

Fortunately, `stream.js` doesn't error when taking or dropping more from a stream than it
has, making the solution pretty easy.
However, since the only documentation `stream.js` has is the [website](http://streamjs.org/) and
source code, it took way longer than necessary to figure out.

Let's take [the code that sends JSON data to codecov](https://github.com/dionyziz/stream.js/blob/master/external/sendtocodecov.js) as the second example.
[sendtocodecov.js](https://github.com/dionyziz/stream.js/blob/master/external/sendtocodecov.js) reads the coverage.json file that is generated with `npm test`.
It then starts the codecov code in a child process and pipe the JSON data to its stdin
stream. It does that because the codecov code will throw an error if run locally,
complaining that it can't find the CODECOV_TOKEN environment variable. Resulting in a not
so pleasent error whenever we run the test suit with coverage.

```
Lines        : 83.93% ( 141/168 )
================================================================================
C:\Users\dotnet\Projects\opensource\stream.js\node_modules\codecov.io\lib\getConfiguration.js:27
      throw new Error("unknown service. could not get configuration");
      ^

Error: unknown service. could not get configuration
    at module.exports (C:\Users\dotnet\Projects\opensource\stream.js\node_modules\codecov.io\lib\getConfiguration.js:27:13)
    at sendToCodecov (C:\Users\dotnet\Projects\opensource\stream.js\node_modules\codecov.io\lib\sendToCodeCov.io.js:11:15)
    at Socket.<anonymous> (C:\Users\dotnet\Projects\opensource\stream.js\node_modules\codecov.io\bin\codecov.io.js:14:5)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
npm ERR! Test failed.  See above for more details.
```

It works but it is written in an imperative style and since we can read the JSON
data as a stream, why not utilize `stream.js`?

We need to change the `fs.readFile` to create a stream and then we need to build our
`stream.js` stream from it.

By looking at the API we can try and guess what method will add to a stream. `add` is
there so let's try with that.

``` js
var coverageDataStream = fs.createReadStream(coveragePath, { encoding: 'utf8' });
var stream = new Stream(null);
coverageDataStream.on('data', function(data) {
  stream.add(Stream.make(data));
});
coverageDataStream.on('end', function() {
  stream.print();
});
coverageDataStream.read();
```

The above will print nothing but `null`. We have to know that `stream.js` work with immutable
data, so any method wont mutate the stream but return a new stream object. If you have a FP
background that might be obvious, if not then you're left scratching your head. Knowing this,
we set the return stream of `add` to our stream variable.

`stream = stream.add(Stream.make(data));` 

This looks good. We're getting our data. But there is a `null` value right at the top. Let's
create an empty stream and add to that instead of our `null` stream. Turns out we can't.

```
C:\Users\dotnet\Projects\opensource\stream.js\lib\index.js:35
            throw new Error('Cannot use item() on an empty stream.');
```

Ok, but we can just take the value of interest, namely the second value. Instead of `print`
we use `console.log` to print out our desired data. `console.log(stream.item(1))` But this gives
us an error, `Error: Item index does not exist in stream.` It is now clear that `add` isn't
the right method to use. `add` will add a value to the `head` of our stream. But there is
also `append`. Let's see.

``` js
var coverageDataStream = fs.createReadStream(coveragePath, { encoding: 'utf8' });
var stream = new Stream(null);
coverageDataStream.on('data', function(data) {
  stream = stream.append(Stream.make(data));
});
coverageDataStream.on('end', function() {
  console.log(stream.item(1))
});
coverageDataStream.read();
```

This of course only works if we read all the JSON data in one go. So let's quickly change
`item` to `drop(1)` and pass the stream to `pipeToCodeCov`.

A final solution could look like below. It still isn't FP as we have no pure functions but
it does use `stream.js`.

``` js
#!/usr/bin/env node

'use strict';

var Stream = require('../lib/index');
var fs = require('fs');
var spawn = require('child_process').spawn;
var path = require('path');
var coveragePath = path.resolve(__dirname, '..', 'coverage/coverage.json');
var coverageDataStream = fs.createReadStream(coveragePath, { encoding: 'utf8' });
var stream = new Stream(null);

coverageDataStream.on('data', function(data) {
  stream = stream.append(Stream.make(data));
});
coverageDataStream.on('end', function() {
  stream = stream.drop(1);
  pipeToCodeCov(stream);
});
coverageDataStream.read();

function pipeToCodeCov(jsonStream) {
  var codecov = 'node_modules/.bin/codecov';
  var child;
  var node = process.execPath;
  var codecov = path.resolve(__dirname, '..', codecov);
  child = spawn(node, [codecov], { stdio: 'pipe' });
  child.on('error', function(data) {
    console.error('codecov lib is not accessible');
  });
  child.stdout.on('data', function(data) {
    console.log(data.toString());
  });
  child.stdin.setEncoding = 'utf8';
  jsonStream.walk(function(json) {
    child.stdin.write(json);
  })
  child.stdin.end();
}
```

My main point is that `stream.js` seriously lacks documentation. I also feel that the
[website](http://streamjs.org/) could explain a little about how `stream.js` deals with immutable data.
Debugging `stream.js` to get answers, is like running through a maze. Don't get me wrong,
I really like `stream.js` and how its implementation doesn't rely on arrays. I'm just saying
that the learning curve is rather steep when you don't have a FP background, even though
the [website](http://streamjs.org/) is enjoyable to read but unfortunately not very comprehensive.

**Comment by dotnetCarpenter** [comment]
One improvement to `stream.js` could be to allow methods to work on empty Streams. I haven't thought about how that could be implemented yet. But it would make example two easier and alleviate a potential bug in the first example, where the data contain lots of new lines and `options.newline == false` which would exhaust the call stack.

**Comment by dionyziz** [comment]
@dotnetCarpenter You're quite right about the lack of documentation. Since you have put quite a lot of time and effort to figure out how the library works, I think you are rather the right person to write it.

If you want, I can put the stream.js website source code on GitHub also (what would be a good place for that? not sure if the same repo is right) so that you can contribute.

Other than that, I think since the website is introductory, we could create a reference API somewhere. Perhaps the wiki pages offered by GitHub could be one way to do it.

What are your thoughts?

**Comment by dotnetCarpenter** [comment]
I think the README is the right place for an API description. `stream.js` API is not vast and it is the first thing you want to know as a developer.

I'm not against the idea of contributing to docs, but since I'm new to `strams.js`, I hoped that you could do a superficial API description and I could then fill in. It would save me a lot of time and (probably) make the API doc less prone to errors. We could use the wiki for extended examples etc. which in turns might make their way into the website.

As for the website code, I think it should be in a separate repo. **stream.js-website** Where do you host it now? If the website was in a github repo, it could me easier to use [gh-pages](https://pages.github.com/).

**Comment by dionyziz** [comment]
OK, I'll do a sketch for the API.

stream.js-website sounds good, let's do that. I've [created a repo](https://github.com/dionyziz/stream.js-website) for this where I'll upload the files soon.

I host it on my own server, but gh-pages sounds like a good option – let's plan to migrate there.

**Comment by dionyziz** [comment]
I'm attaching a short description of each function here as a comment. You can take these notes and develop it into a fuller documentation API. I think adding some examples would make it much better. Thanks so much for your work on this!

As a sidenote, I think we should change the order of items passed to the argument function of zip (maybe you can take a look at this or create an issue and I can take a look). Looking at the code, I also noticed some coding style inconsistencies (spacing, indentation) which should be fixed.

`new Stream(head, tailPromise)`: Creates a new stream with the given *head* and tail. The tail is provided as a promise *tailPromise*, in the form of a function that returns the tail. This allows a powerful abstraction in the form of lazy streams, which enable features such as infinite streams.

`new Stream()`: Creates a new empty stream (a stream with no elements).

Object methods:

`empty()`: Checks if the stream is empty and returns a boolean value. This returns false for the empty stream and true for non-empty finite or infinite streams.

`head()`: Returns the head of the stream (its first element). The stream must not be empty.

`tail()`: Returns the tail of the stream; this is a stream with all elements except the first. The stream must not be empty.

`item(n)`: Returns the *n*-th item of the stream. The stream must not be empty for this method to be used. If the item does not exist in the stream, an error is thrown. Items of infinite streams can be accessed using this method.

`length()`: Returns the length of a finite stream. This operation has undefined behavior for infinite streams.

`add(s)`: Returns a new stream the elements of which are obtained by summing the current stream with the stream *s*. Infinite streams can be added. If there are extraneous items in one of the streams, the other stream is assumed to be filled up with zeroes to be added.

`append(s)`: Creates a new stream whose items consist of the items of the current stream followed by the items of stream *s*. If the current stream is infinite, it returns the current stream. Appending an infinite stream to a finite stream produces an infinite stream.

`zip(f, s)`: Zips the elements of two streams using function *f*. Returns a new stream. This new stream contains one item for each item of the current stream. The new items are produced by zipping an item from the current stream with an item from stream *s*. The zipping happens by applying function *f* between the items from these two streams. *f* is called with two stream items as a parameter: The first parameter given to it is an item from *s*, while the second parameter given to it is an item from the current stream. If there are extraneous items in either the current stream or stream *s* (i.e. if one stream has more items than the other), these are appended at the end. Infinite streams can be zipped.

`map(f)`: Applies function *f* to each element of the current stream and returns a stream of the mapped values. Infinite streams can be mapped.

`concatmap(f)`: Applies the function *f* to each element of the stream. Then concatenates all the resulting elements into one big stream which is returned. *f* is applied to each element and is expected to return a stream result.

`reduce(aggregator, [initial])`: Aggregates the stream elements into a single value through function *aggregator*. This is known in other languages as a *fold* or the *reduce* operation in map/reduce. It applies the aggregator function in the currently aggregated value (which starts at *initial*) and a stream item to produce a new aggregated value. When all items have been aggregated, it returns the result. If the initial value is omitted, the first element of the stream is taken as the initial value and the fold is applied on the rest of the stream. In this case, the stream must be non-empty. Requires a finite stream.

`sum()`: Returns the sum of the items of the stream. Requires a finite stream.

`walk(f)`: Walks the stream items by applying function *f* on them. Equivalent to a for loop over the stream, this forces eager evaluation on the stream. Requires a finite stream.

`force()`: Forces eager evaluation of the stream. All tails are evaluated until the end of the stream. Requires a finite stream.

`scale(factor)`: Returns a new stream in which all items have been multiplied by the given *factor*.

`filter(f)`: Filters the stream items by function *f*. Returns a new stream with the filtered items. *f* takes a single stream item and returns `true` or `false`. Only items for which it returns `true` are kept. Infinite streams can be filtered.

`take(n)`: Returns a new stream which contains only the first *n* items of the current stream. This can be applied on an infinite stream to produce a finite stream. If the stream does not contain enough items to take, those that can be taken are returned and no error is produced.

`drop(n)`: Returns a new stream that does not contain the first *n* items of the current stream. If the current stream contains less than *n* items, an empty stream is returned. Dropping items from an infinite stream produces an infinite stream.

`member(x)`: Checks if *x* is a member of the stream. Returns `true` if x exists in the stream or `false` otherwise. Requires a finite stream.

`print([n])`: Prints the elements of the stream in the console for debugging purposes. If *n* is provided, only *n* elements are printed.

Class methods:

`makeOnes()`: Returns an infinite stream filled with the number 1.

`makeNaturalNumbers()`: Returns the infinite stream of natural numbers: 1, 2, 3, ...

`make(a1, a2, ..., an)`: Returns a stream which contains the items specified in the function parameters. The stream contains exactly *n* items, where *n* is the number of arguments passed to the function.

`make([a1, a2, ..., an])`: Returns a stream which contains the items from the specified array. The stream contains exactly *n* items where *n* is the number of elements in the array specified.

`range([low], [high])`: Returns a stream containing the integer numbers in the range *low*...*high* inclusive. The resulting stream contains exactly `high - low + 1` items. If *low* is omitted, it is assumed to be 1. If high is omitted, an infinite range is produced, with no upper bound.

`equals(s1, s2)`: Checks if two streams are equal. Two streams are equal when they have the same number of elements and each two elements in the same positions are equal.

**Comment by dotnetCarpenter** [comment]
Great! I'm getting very excited about this. I think the best way, going forward, would be to create a `doc` branch and incorporate your API description into the README. Then you can review it and we can merge it in when done.

The past two weeks has been "off work" for me and I've had the privilege to update two beauties I've found. `stream.js` being one and [traits.js](https://github.com/dotnetcarpenter/traits.js) being the other. And I actually started out by looking at build systems, [which is kinda of broken for front end development](https://medium.com/@trek/last-week-i-had-a-small-meltdown-on-twitter-about-npms-future-plans-around-front-end-packaging-b424dd8d367a) at the moment.

Unfortunately,I won't have much time the next couple of months but I'll prioritize getting `stream.js` into production ready shape* and plan to use it whenever it make sense.

Just a heads-up, that my contribution pace will slow down.

*By production ready, I mean `stream.js` should be easily included in a new project, be well tested (having a bit higher code coverage) and have documentation.

**Comment by dionyziz** [comment]
Sounds like a plan :)

**Comment by dotnetCarpenter** [comment]
Using `[]` for both meaning optional and array is ambiguous. I know that `[]` is a common convention for optional but I'm just wondering how to make a clear distinction from array literal. Any ideas?

**Comment by dionyziz** [comment]
You're right. Let's just denote optional arguments when describing them and
remove the ambiguous notation. Use [] only for arrays.

**Comment by GeorgeGkas** [comment]
I'll close this issue for the favor of issues [#5](https://github.com/dionyziz/stream.js-website/issues/5) and [#4](https://github.com/dionyziz/stream.js-website/issues/4) of the official [stream.js website repo](https://github.com/dionyziz/stream.js-website). Please refer to those issues for updates.
